forms/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from rest_framework import routers

from core import views
from core import viewsets

admin.site.site_header = 'Forms beheer'
admin.site.enable_nav_sidebar = False

router = routers.DefaultRouter()
router.register(r'forms', viewsets.FormViewSet)
router.register(r'responses', viewsets.ResponseViewSet)

urlpatterns = [
    path('', views.index, name='dashboard'),
    path('forms/create', views.create_form, name='create_form'),
    path('forms/<int:form_id>', views.view_form, name='view_form'),
    path('forms/<int:form_id>/edit', views.edit_form, name='edit_form'),
    path('forms/<int:form_id>/duplicate', views.duplicate_form, name='duplicate_form'),
    path('forms/<int:form_id>/delete', views.delete_form, name='delete_form'),
    path('forms/<int:form_id>/introduction', views.introduction_form, name='introduction_form'),
    path('forms/<int:form_id>/introduction/<uuid:code>', views.introduction_form, name='introduction_form'),
    path('forms/<int:form_id>/request_access', views.request_access, name='request_access'),
    path('forms/<int:form_id>/fill', views.fill_form, name='fill_form'),
    path('forms/<int:form_id>/fill/<uuid:code>', views.fill_form, name='fill_form'),
    path('forms/<int:form_id>/embed', views.embed_form, name='embed_form'),
    path('forms/<int:form_id>/validate_email/<uuid:code>', views.validate_respondent_email, name='validate_respondent_email'),
    path('forms/<int:form_id>/preview', views.preview_form, name='preview_form'),
    path('forms/<int:form_id>/fill/download/xlsx', views.user_download_form_xlsx, name='user_download_form_xlsx'),
    path('forms/<int:form_id>/fill/download/xlsx/<int:response_id>', views.user_download_form_xlsx, name='user_download_form_xlsx'),
    path('forms/<int:form_id>/fill/download/docx', views.user_download_form_docx, name='user_download_form_docx'),
    path('forms/<int:form_id>/fill/download/docx/<int:response_id>', views.user_download_form_docx, name='user_download_form_docx'),
    path('forms/<int:form_id>/fill/download/pdf', views.user_download_form_pdf, name='user_download_form_pdf'),
    path('forms/<int:form_id>/fill/download/pdf/<int:response_id>', views.user_download_form_pdf, name='user_download_form_pdf'),
    path('forms/<int:form_id>/answers', views.form_answers, name='form_answers'),
    path('forms/<int:form_id>/respondents', views.form_respondents, name='form_respondents'),
    path('forms/<int:form_id>/respondents/create', views.form_respondents_create, name='form_respondents_create'),
    path('forms/<int:form_id>/actions', views.form_actions, name='form_actions'),
    path('forms/<int:form_id>/actions/create', views.form_actions_create, name='form_actions_create'),
    path('respondents/<int:respondent_id>/remind', views.remind_respondent, name='remind_respondent'),
    path('respondents/<int:respondent_id>/delete', views.delete_respondent, name='delete_respondent'),
    path('actions/<int:action_id>/edit', views.edit_action, name='edit_action'),
    path('actions/<int:action_id>/delete', views.delete_action, name='delete_action'),
    path('response/<int:response_id>/delete', views.delete_response, name='delete_response'),
    path('forms/<int:form_id>/export', views.admin_export_form, name='admin_export_form'),
    path('attachments/create', views.create_attachment, name='create_attachment'),
    path('oidc/', include('mozilla_django_oidc.urls')),
    path('api/v1/', include(router.urls)),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

core/models.py
import os
import uuid

from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.functional import lazy
from django.utils.translation import gettext_lazy as _
from django.db.models import JSONField
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
import reversion
from .lib import get_actions_from_apps
from .validators import validate_file_extension

MAX_URL_LENGTH = 2000


class UserManager(BaseUserManager):
    def create_user(self, full_name, email, password=None):
        if not full_name:
            raise ValueError('Users must have a full name')

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            full_name=full_name,
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, full_name, email, password=None):
        user = self.create_user(
            full_name=full_name,
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    full_name = models.CharField(max_length=255, db_index=True)
    email = models.EmailField(verbose_name='email address', unique=True)
    picture_url = models.CharField(
        max_length=MAX_URL_LENGTH, blank=True, default='')
    external_id = models.CharField(max_length=255, unique=True, null=True)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    class Meta:
        ordering = ['full_name']

    def __str__(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        # pylint: disable=unused-argument
        return True

    def has_module_perms(self, app_label):
        # pylint: disable=unused-argument
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def to_dict(self):
        return {
            'id': self.id,
            'full_name': self.full_name
        }


def validate_fields(fields):  # pylint: disable=too-many-branches
    if not isinstance(fields, list):
        raise ValidationError('Moet een lijst van velden zijn')

    if len(fields) > 255:
        raise ValidationError('Aantal velden mag maximaal 255 zijn')

    last_heading = 1  # stands for h1

    for number, field in enumerate(fields, start=1):  # pylint: disable=too-many-nested-blocks
        if not isinstance(field, dict):
            raise ValidationError(f'Veld {number} is geen object')

        element = field.get('element')

        if element == 'field':
            for required_field in ['id', 'label']:
                if not field.get(required_field):
                    raise ValidationError(
                        f'Veld {number} heeft geen {required_field}')

            if field.get('type') == 'array':
                used_fields = []

                for sub_number, sub_field in enumerate(field.get('fields'), start=1):
                    for required_field in ['id', 'label']:
                        if not sub_field.get(required_field):
                            raise ValidationError(
                                f'Veld {number}.{sub_number} heeft geen {required_field}')

                    sub_field_id = sub_field.get('id')

                    if sub_field_id in used_fields:
                        raise ValidationError(
                            f'Veld {number}.{sub_number} bevat het interne id {sub_field_id}, maar deze wordt reeds gebruikt.')

                    used_fields.append(sub_field_id)

            continue

        if element in ['h2', 'h3', 'h4', 'p']:
            for required_field in ['value']:
                if not field.get(required_field):
                    raise ValidationError(
                        f'Veld {number} heeft geen {required_field}')

            if element in ['h2', 'h3', 'h4']:
                heading = int(element[1:])
                if heading > last_heading and (heading - 1) != last_heading:
                    raise ValidationError(
                        f'Kop {number}. Element h{heading} mag niet onder h{last_heading} vallen')

                last_heading = heading

            continue

        raise ValidationError(f'Veld {number} heeft onbekend type "{element}"')

    used_fields = []
    for number, field in enumerate(fields, start=1):
        field_id = field.get('id')

        if not field_id:
            continue

        if field.get('element') != 'field':
            continue

        if field_id in used_fields:
            raise ValidationError(
                f'Veld {number} bevat het interne id {field_id}, maar deze wordt reeds gebruikt.')

        used_fields.append(field_id)


def upload_to_logo(_, filename):
    dirname = timezone.now().strftime('logos/%Y/%m/%d/')
    return os.path.join(dirname, get_random_string(length=24), filename)


@reversion.register()
class Form(models.Model):
    class Access(models.TextChoices):
        OPEN = 'OPEN', _('Open')
        CLOSED = 'CLOSED', _('Gesloten')

    title = models.CharField(max_length=255)
    is_published = models.BooleanField(default=False)
    opening_date = models.DateTimeField(blank=True, null=True)
    closing_date = models.DateTimeField(blank=True, null=True)
    is_response_downloadable = models.BooleanField(default=True)
    respondent_can_request_access = models.BooleanField(default=False)
    respondent_can_preview_form = models.BooleanField(default=False)
    respondent_require_email_validation = models.BooleanField(default=False)
    fields = JSONField(default=list, blank=True, validators=[validate_fields])
    managers = models.ManyToManyField(
        'User', related_name='managed_forms', blank=True)
    access = models.CharField(
        max_length=20, choices=Access.choices, default=Access.OPEN)
    logo = models.ImageField(upload_to=upload_to_logo, blank=True, null=True)

    invitation_mail_subject = models.CharField(
        max_length=255, blank=True, null=True)
    invitation_mail_message = models.TextField(blank=True, null=True)

    introduction = models.TextField(blank=True, null=True)

    thank_you_message = models.TextField(blank=True, null=True)

    email_confirmation_subject = models.CharField(
        max_length=255, blank=True, null=True)
    email_confirmation_message = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def is_closed(self):
        current_time = timezone.now()

        if self.opening_date and current_time < self.opening_date:
            return True
        if self.closing_date and current_time > self.closing_date:
            return True

        return False

    def get_fields(self):
        return [f for f in self.fields if f.get('element') == 'field']

    def to_dict(self):
        return {
            'id': self.pk,
            'title': self.title,
        }


@reversion.register()
class Response(models.Model):
    form = models.ForeignKey(
        'Form', on_delete=models.CASCADE, related_name='responses')
    data = JSONField(default=dict)
    respondent = models.ForeignKey(
        'Respondent', on_delete=models.SET_NULL, related_name='responses', null=True)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def export_data(self):
        for field in self.form.get_fields():
            value = self.data.get(field.get('id'))

            if isinstance(value, dict) and value.get('_files'):
                yield list(Attachment.objects.filter(file__in=value.get('_files')))
            else:
                yield value


class Respondent(models.Model):
    form = models.ForeignKey(
        'Form', on_delete=models.CASCADE, related_name='respondents')
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(verbose_name='email address')
    code = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    last_notification = models.DateTimeField(
        auto_now_add=True, blank=True, null=True)

    def __str__(self):
        return f'{self.full_name} <{self.email}>'

    def to_dict(self):
        return {
            'id': self.pk,
            'full_name': self.full_name,
            'email': self.email,
            'phone': self.phone,
            'code': self.code,
            'last_notification': self.last_notification,
            'has_responded': self.responses.count() > 0
        }


def upload_to_attachment(_, filename):
    dirname = timezone.now().strftime('attachments/%Y/%m/%d/')
    return os.path.join(dirname, get_random_string(length=24), filename)


class Attachment(models.Model):
    response = models.ForeignKey(
        'Response', on_delete=models.CASCADE, related_name='attachments', null=True, blank=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    file = models.FileField(upload_to=upload_to_attachment, validators=[
                            validate_file_extension])

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.name:
            self.name = os.path.basename(self.file.name)

        super().save(force_insert=force_insert,
                     force_update=force_update, using=using, update_fields=update_fields)

    def __str__(self):
        return self.name


class Action(models.Model):
    form = models.ForeignKey(
        'Form', on_delete=models.CASCADE, related_name='actions')

core/forms.py
from django import forms
from django.forms.widgets import DateTimeInput

from .models import Form, Respondent, Action


class FormForm(forms.ModelForm):
    class Meta:
        model = Form
        fields = [
            'title',
            'logo',
            'access',
            'is_published',
            'opening_date',
            'closing_date',
            'is_response_downloadable',
            'respondent_can_request_access',
            'respondent_can_preview_form',
            'respondent_require_email_validation',
            'fields',
            'managers',
            'introduction',
            'invitation_mail_subject',
            'invitation_mail_message',
            'thank_you_message',
            'email_confirmation_subject',
            'email_confirmation_message',
        ]

    # format the date string in a way that `<input type="datetime-local" />` expects
    opening_date = forms.DateTimeField(widget=DateTimeInput(format='%Y-%m-%dT%H:%M'), required=False)
    closing_date = forms.DateTimeField(widget=DateTimeInput(format='%Y-%m-%dT%H:%M'), required=False)


class RespondentForm(forms.ModelForm):
    send_email_notification = forms.BooleanField(required=False, initial=True)

    class Meta:
        model = Respondent
        fields = ['full_name', 'email', 'phone']


class CreateActionForm(forms.ModelForm):
    class Meta:
        model = Action
        fields = ['key', 'args']


class EditActionForm(forms.ModelForm):
    class Meta:
        model = Action
        fields = ['args']


class DuplicateFormForm(forms.Form):
    title = forms.CharField(label='Titel', max_length=100)
    copy_respondents = forms.BooleanField(
        label='Kopieer respondenten', required=False)
    copy_answers = forms.BooleanField(
        label='Kopieer antwoorden', required=False)
    copy_actions = forms.BooleanField(label='Kopieer acties', required=False)

forms/asgi.py
"""
ASGI config for forms project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/howto/deployment/asgi/
"""

import os
from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter, URLRouter
from django.core.asgi import get_asgi_application
from django.urls import re_path
from .consumers import UpdateConsumer

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'forms.settings')

django_asgi_app = get_asgi_application()

websocket_urlpatterns = [
    re_path(r'ws/forms/(?P<form_id>\w+)/updates/(?P<code>[a-z0-9-]+)$', UpdateConsumer.as_asgi()),
]

application = ProtocolTypeRouter({
    'http': django_asgi_app,
    'websocket': AuthMiddlewareStack(
        URLRouter(
            websocket_urlpatterns
        )
    )
})

forms/celery.py
import os

from celery import Celery

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'forms.settings')

app = Celery('forms')
app.config_from_object('django.conf:settings', namespace='CELERY')

app.autodiscover_tasks()

forms/wsgi.py
"""
WSGI config for forms project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'forms.settings')

application = get_wsgi_application()

core/templates/_base_no_nav.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!doctype html>
<html lang="nl">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{% if title %}{{ title }} · {% endif %}Forms</title>
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

    {% render_bundle 'app' %}
  </head>

  <body class="antialiased font-sans {% if background == 'gray' %}bg-gray-100{% endif %}">
    {% block header %}{% endblock %}
    <main>
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

core/templates/create_form.html
{% extends '_base.html' %}

{% block content %}
    <div class="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <h2 class="text-2xl leading-8 font-semibold text-gray-900 sm:text-3xl sm:leading-9">
            Nieuw formulier
        </h2>

        <form method="POST" action="{% url 'create_form' %}">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}

            <div class="mt-6">
                <label for="id_title" class="block text-sm font-medium leading-5 text-gray-700">
                    Titel
                </label>
                <div class="mt-1 rounded-md shadow-sm">
                    {{ form.title }}
                </div>
                {% for error in form.title.errors %}
                    <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="mt-6">
                <label for="id_fields" class="block text-sm font-medium leading-5 text-gray-700">
                  Velden
                </label>
                <div id="js-editor-entry-point" class="mt-1"></div>
                {{ js_editor|json_script:"js-editor-data" }}
            </div>

            <div class="mt-6">
                <label for="id_access" class="block text-sm font-medium leading-5 text-gray-700">
                    Toegang
                </label>
                <div class="mt-2">
                    <div class="relative flex items-start">
                        <div class="absolute flex items-center h-5">
                            <input id="open" type="radio" name="access" class="form-radio h-4 w-4 text-blue-600 transition duration-150 ease-in-out" value="OPEN" {% if form.access.value == 'OPEN'%}checked{% endif%}>
                        </div>
                        <div class="pl-7 text-sm leading-5">
                            <label for="open" class="font-medium text-gray-700">Open</label>
                            <p class="text-gray-500">Het formulier kan door iedereen met de link ingevuld worden.</p>
                        </div>
                    </div>
                    <div class="relative flex items-start mt-2">
                        <div class="absolute flex items-center h-5">
                            <input id="closed" type="radio" name="access" class="form-radio h-4 w-4 text-blue-600 transition duration-150 ease-in-out" value="CLOSED" {% if form.access.value == 'CLOSED'%}checked{% endif%}>
                        </div>
                        <div class="pl-7 text-sm leading-5">
                            <label for="closed" class="font-medium text-gray-700">Gesloten</label>
                            <p class="text-gray-500">Het formulier kan op uitnodiging ingevuld worden.</p>
                        </div>
                    </div>
                </div>

                {% for error in form.access.errors %}
                    <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_is_published" class="block text-sm font-medium leading-5 text-gray-700">Publiceren?</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.is_published }}
                    </div>
                </div>
                {% for error in form.is_published.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center">
                        <label for="id_opening_date" class="block text-sm font-medium leading-5 text-gray-700">Openingsdatum</label>
                        <p class="text-gray-500 text-sm max-w-sm">De datum vanaf wanneer het gepubliceerde formulier ingevuld kan worden. Bij een lege waarde wordt dit genegeerd.</p>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.opening_date }}
                    </div>
                </div>
                {% for error in form.opening_date.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center">
                        <label for="id_closing_date" class="block text-sm font-medium leading-5 text-gray-700">Sluitingsdatum</label>
                        <p class="text-gray-500 text-sm max-w-sm">De datum tot wanneer het gepubliceerde formulier ingevuld kan worden. Bij een lege waarde wordt dit genegeerd.</p>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.closing_date }}
                    </div>
                </div>
                {% for error in form.closing_date.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_is_response_downloadable" class="block text-sm font-medium leading-5 text-gray-700">Gebruiker kan ingevuld formulier downloaden</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.is_response_downloadable }}
                    </div>
                </div>
                {% for error in form.is_response_downloadable.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_respondent_can_request_access" class="block text-sm font-medium leading-5 text-gray-700">Gebruiker kan toegang aanvragen (bij gesloten formulier)</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.respondent_can_request_access }}
                    </div>
                </div>
                {% for error in form.respondent_can_request_access.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_respondent_can_preview_form" class="block text-sm font-medium leading-5 text-gray-700">Gebruiker kan een voorvertoning bekijken (bij gesloten formulier)</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.respondent_can_preview_form }}
                    </div>
                </div>
                {% for error in form.respondent_can_preview_form.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_respondent_require_email_validation" class="block text-sm font-medium leading-5 text-gray-700">Gebruiker moet nogmaals inloggen (extra beveiliging bij gesloten formulier)</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.respondent_require_email_validation }}
                    </div>
                </div>
                {% for error in form.respondent_require_email_validation.errors %}
                    {{ error }}
                {% endfor %}
            </div>

            <button type="submit" class="mt-6 btn-primary">
                Opslaan
            </button>
        </form>
    </div>
{% endblock %}

core/templates/duplicate_form.html
{% extends '_base.html' %}

{% block content %}
    <div class="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <h2 class="text-2xl leading-8 font-semibold text-gray-900 sm:text-3xl sm:leading-9">
            Formulier dupliceren
        </h2>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field.errors }}
                {{ hidden_field }}
            {% endfor %}

            <div class="mt-6">
                <div class="mt-1 rounded-md shadow-sm">
                    <label for="id_title" class="block text-sm font-medium leading-5 text-gray-700">
                        Titel
                    </label>
                    {{ form.title }}
                </div>
                {% for error in form.title.errors %}
                    <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_copy_respondents" class="block text-sm font-medium leading-5 text-gray-700">Kopieer respondenten</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.copy_respondents }}
                    </div>
                </div>

                {% for error in form.copy_respondents.errors %}
                    <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_copy_answers" class="block text-sm font-medium leading-5 text-gray-700">Kopieer antwoorden</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.copy_answers }}
                    </div>
                </div>

                {% for error in form.copy_answers.errors %}
                    <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="mt-6">
                <div class="relative flex items-start">
                    <div class="items-center h-5">
                        <label for="id_copy_actions" class="block text-sm font-medium leading-5 text-gray-700">Kopieer acties</label>
                    </div>
                    <div class="pl-7 text-sm leading-5">
                        {{ form.copy_actions }}
                    </div>
                </div>

                {% for error in form.copy_actions.errors %}
                    <p class="mt-2 text-sm text-red-600">{{ error }}</p>
                {% endfor %}
            </div>

            <div class="mt-6 flex justify-between">
                <button type="submit" class="btn-primary">
                    Dupliceren
                </button>
            </div>
        </form>
    </div>
{% endblock %}

core/templates/form_respondents_create.html
{% extends '_base.html' %}

{% block header %}
  {% include 'partials/form_header.html' %}
{% endblock %}

{% block content %}
  <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
    <form method="POST">
      {% csrf_token %}

      {{ respondent_form.non_field_errors }}

      {% for hidden_field in respondent_form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
      {% endfor %}

      <div class="mt-6">
        <div class="mt-1 rounded-md shadow-sm">
            <label for="id_full_name" class="block text-sm font-medium leading-5 text-gray-700">
                Volledige naam*
            </label>
            {{ respondent_form.full_name }}
        </div>
        {% for error in respondent_form.full_name.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
        {% endfor %}
      </div>

      <div class="mt-6">
        <div class="mt-1 rounded-md shadow-sm">
            <label for="id_email" class="block text-sm font-medium leading-5 text-gray-700">
                E-mailadres*
            </label>
            {{ respondent_form.email }}
        </div>
        {% for error in respondent_form.email.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
        {% endfor %}
      </div>

      <div class="mt-6">
        <div class="mt-1 rounded-md shadow-sm">
            <label for="id_phone" class="block text-sm font-medium leading-5 text-gray-700">
                Telefoonnummer
            </label>
            {{ respondent_form.phone }}
        </div>
        {% for error in respondent_form.phone.errors %}
            <p class="mt-2 text-sm text-red-600">{{ error }}</p>
        {% endfor %}
      </div>


      <div class="mt-6">
        <div class="relative flex items-start">
            <div class="items-center h-5">
                <label for="id_send_email_notification" class="block text-sm font-medium leading-5 text-gray-700">Verstuur e-mailnotificatie</label>
            </div>
            <div class="pl-7 text-sm leading-5">
                {{ respondent_form.send_email_notification }}
            </div>
        </div>
        {% for error in respondent_form.send_email_notificatio.errors %}
            {{ error }}
        {% endfor %}
      </div>

      <button type="submit" class="mt-6 btn-primary">
        Opslaan
      </button>
    </form>
  </div>
{% endblock %}